### PR TITLE
Configurable external urls

### PR DESCRIPTION
**Pull request by torsten-bit**
Hi,

first of all, thank you for making working with AXE and HtmlCS so easy.

We run accessibility-tests within our new build-environment which does not have access to the internet. Therefore we would like to get the js-scripts from another server. I made the urls configurable, defaulting to the current behavior.

Kind regards
Torsten

### CODE REVIEW

**Comment by torsten-bit** [comment]
Seems to me that the codacy api token is missing or maybe outdated?

**Comment by sridharbandi** [comment]
@torsten-bit 

Does this work around works for you ? https://github.com/sridharbandi/Java-a11y/issues/26#issuecomment-1412300401

**Comment by torsten-bit** [comment]
Hi @sridharbandi. yes this would work, but it seems to be a lot of manual effort to get it working. Moreover we would not benefit from any future updates. Therefore we would like to have a way to customize the injection of the resources.

**Comment by sridharbandi** [comment]
> Hi @sridharbandi. yes this would work, but it seems to be a lot of manual effort to get it working. Moreover we would not benefit from any future updates. Therefore we would like to have a way to customize the injection of the resources.

@torsten-bit I will test the changes and will create a release in couple of days.
Thank you for your contribution.

**Comment by torsten-bit** [comment]
I just found a small typo and fixed that.

**Comment by sridharbandi** [comment]
@torsten-bit created release v3.0.4. Thank you for your contribution 👍 . Star it if you find this project useful, and share it in your QA circle.

**Pull request merged**
